"""Acceptance report for the /words feed on MACULA (NC exit, step 3b; design: internal-docs/nc-exit-step3-structure-design.md).

Compares cf_engine.list_words_filtered (BHSA locally; Nestle1904 through the live service) with words_macula.list_words_filtered:

  1. POS      the BHSA `sp` of every bridged token against the code words_macula derives from MACULA (agreement, and the classes that disagree)
  2. STEM     the same for the verbal stem
  3. POOLS    total_pool for fixed filter sets (token counts differ: MACULA keeps prefixes and suffixes as tokens of their own, so BHSA words that fuse them do not exist there)
  4. FREQUENCY the 150 most frequent distinct lexemes (as Strong's numbers): overlap of the two feeds
  5. GLOSSES  lexemes the German glosses cover under each base, and the pool a German request sees
  6. SPEED    median ms per request

  cd shoresh && .venv/bin/python3 -m macula.compare_words_bases [--out ../internal-docs/words-base-comparison.md]
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import sqlite3
import statistics
import sys
import time
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
LIVE = os.environ.get("SHORESH_LIVE", "https://shoresh.qombi.com")
QUERIES = [
    ("Hebrew verbs", dict(corpus="hebrew", language="Hebrew", pos=["verb"])),
    ("Hebrew piel verbs", dict(corpus="hebrew", language="Hebrew", pos=["verb"], stem=["piel"])),
    ("Hebrew qal wayyiqtol", dict(corpus="hebrew", language="Hebrew", pos=["verb"], stem=["qal"], tense=["wayq"])),
    ("Hebrew nouns", dict(corpus="hebrew", language="Hebrew", pos=["subs"])),
    ("Hebrew proper nouns", dict(corpus="hebrew", language="Hebrew", pos=["nmpr"])),
    ("Hebrew prepositions", dict(corpus="hebrew", language="Hebrew", pos=["prep"])),
    ("Hebrew with suffix", dict(corpus="hebrew", language="Hebrew", pos=["subs", "verb"], suffix=True)),
    ("Hebrew rank 0-99", dict(corpus="hebrew", language="Hebrew", min_rank=0, max_rank=99)),
    ("Aramaic", dict(corpus="hebrew", language="Aramaic")),
    ("Greek verbs", dict(corpus="greek", pos=["verb"])),
    ("Greek aorist verbs", dict(corpus="greek", pos=["verb"], tense=["aor"])),
    ("Greek nouns", dict(corpus="greek", pos=["noun"])),
]


def live(params: dict):
    from urllib.parse import urlencode
    q = {"language": {"hebrew": "Hebrew", "greek": "Greek"}[params["corpus"]] if not params.get("language") else params["language"], "limit": 1}
    for k in ("pos", "stem", "tense"):
        if params.get(k):
            q[k] = ",".join(params[k])
    for k in ("suffix", "min_rank", "max_rank"):
        if params.get(k) is not None:
            q[k] = str(params[k]).lower()
    for _ in range(3):
        try:
            with urllib.request.urlopen(urllib.request.Request(f"{LIVE}/words?{urlencode(q)}", headers={"User-Agent": "bcv-query-acceptance/1.0 (curl-compatible)"}), timeout=90) as r:
                return json.loads(r.read())
        except Exception:
            time.sleep(3)
    return {}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=HERE.parents[1] / "internal-docs" / "words-base-comparison.md")
    a = ap.parse_args()
    import data
    import trees_macula
    import words_macula as wm
    if not trees_macula.available():
        print("trees-macula.db not found"); return 1
    from corpus_engine import engine
    L = [f"# /words feed: BHSA / Nestle1904 engine vs MACULA ({time.strftime('%Y-%m-%d')})", "",
         "Generated by `shoresh/macula/compare_words_bases.py`. Hebrew: local BHSA engine. Greek: the live service.", ""]

    # 1./2. pos and stem agreement through the bridge
    t = sqlite3.connect(f"file:{trees_macula.trees_path()}?mode=ro", uri=True)
    t.execute("ATTACH DATABASE ? AS sp", (f"file:{__import__('lexeme_macula').spine_path()}?mode=ro",))
    b = sqlite3.connect(f"file:{HERE / 'bhsa-macula-bridge.db'}?mode=ro", uri=True)
    h = sqlite3.connect(f"file:{HERE.parents[1] / 'resources' / 'occurrences' / 'hbo.db'}?mode=ro", uri=True)
    sp = {r[0]: (r[1], r[2]) for r in h.execute("SELECT node, sp, stem FROM occurrence")}
    tok = {r[0]: r[1:] for r in t.execute("SELECT w.key, w.class, w.wtype, s.stem FROM words w JOIN sp.spine_words s ON s.key=w.key WHERE w.corpus='hbo'")}
    agree = n = 0
    stem_agree = stem_n = 0
    bad = collections.Counter()
    for node, key in b.execute("SELECT node, key FROM bridge"):
        if node not in sp or key not in tok:
            continue
        cls, wtype, mstem = tok[key]
        new = wm.bhsa_pos(cls, wtype)
        n += 1
        if new == sp[node][0]:
            agree += 1
        else:
            bad[(cls, wtype, sp[node][0], new)] += 1
        if sp[node][0] == "verb":
            stem_n += 1
            stem_agree += (wm.STEM_CODE.get(mstem, mstem) == sp[node][1])
    L.append("## 1. Part of speech (bridged tokens)")
    L.append(f"- {n} tokens: agreement {100*agree/max(n,1):.1f}% {'PASS' if agree/max(n,1) >= 0.95 else 'CHECK'} (threshold 95%)")
    L.append("- largest disagreements (MACULA class, type -> BHSA sp vs ours): " + "; ".join(f"{k[0]}/{k[1]} -> {k[2]} vs {k[3]}: {v}" for k, v in bad.most_common(6)))
    L.append("")
    L.append("## 2. Verbal stem (BHSA verbs)")
    L.append(f"- {stem_n} verbs: stem agreement {100*stem_agree/max(stem_n,1):.1f}% {'PASS' if stem_agree/max(stem_n,1) >= 0.95 else 'CHECK'} (threshold 95%)")
    L.append("")

    # 3. pools
    L.append("## 3. Pools (total_pool per filter set)")
    L.append("| filter | old base | MACULA | ratio |")
    L.append("|---|---|---|---|")
    ms_old, ms_new = [], []
    for name, q in QUERIES:
        t0 = time.perf_counter()
        new = wm.list_words_filtered(limit=1, **q)
        ms_new.append(1000 * (time.perf_counter() - t0))
        if q["corpus"] == "hebrew":
            t0 = time.perf_counter()
            old = engine.list_words_filtered(limit=1, **{k: v for k, v in q.items() if not (k == "language" and q["corpus"] == "greek")})
            ms_old.append(1000 * (time.perf_counter() - t0))
            o = old["total_pool"]
        else:
            o = live(q).get("total_pool", 0)
        L.append(f"| {name} | {o} | {new['total_pool']} | {new['total_pool']/max(o,1):.2f} |")
    L.append("")

    # 4. frequency overlap
    L.append("## 4. The 150 most frequent distinct lexemes")
    for corpus, lang in (("hebrew", "Hebrew"), ("greek", None)):
        new = wm.list_words_filtered(corpus=corpus, language=lang, limit=150, order="frequency")["words"]
        if corpus == "hebrew":
            old = engine.list_words_filtered(corpus=corpus, language=lang, limit=150, order="frequency")["words"]
            so = {w["strong"] for w in old if w["strong"]}
        else:
            r = None
            try:
                with urllib.request.urlopen(urllib.request.Request(f"{LIVE}/words?language=Greek&limit=150&order=frequency", headers={"User-Agent": "bcv-query-acceptance/1.0 (curl-compatible)"}), timeout=90) as resp:
                    r = json.loads(resp.read())
            except Exception:
                r = {"words": []}
            so = {w["strong"] for w in r["words"] if w.get("strong")}
        sn = {w["strong"] for w in new if w["strong"]}
        j = len(so & sn) / max(len(so | sn), 1)
        L.append(f"- {corpus}: Strong's overlap {len(so & sn)} of {len(so)} old / {len(sn)} new, Jaccard {j:.2f} {'PASS' if j >= 0.7 else 'CHECK'} (threshold 0.70)")
    L.append("")

    # 5. glosses
    L.append("## 5. German glosses")
    old_lex = data.gloss_lexemes("hbo", "German")
    new_lex = data.gloss_lexemes("hbo_lexeme", "German")
    pool_old = engine.list_words_filtered(corpus="hebrew", language="Hebrew", limit=1, lex_filter=old_lex)["total_pool"]
    pool_new = wm.list_words_filtered(corpus="hebrew", language="Hebrew", limit=1, lex_filter=new_lex)["total_pool"]
    full_old = engine.list_words_filtered(corpus="hebrew", language="Hebrew", limit=1)["total_pool"]
    full_new = wm.list_words_filtered(corpus="hebrew", language="Hebrew", limit=1)["total_pool"]
    L.append(f"- lexemes with a German gloss: BHSA-keyed {len(old_lex)}, MACULA-keyed {len(new_lex)}")
    L.append(f"- share of the Hebrew pool a German request keeps: old {100*pool_old/max(full_old,1):.1f}%, MACULA {100*pool_new/max(full_new,1):.1f}% "
             f"{'PASS' if pool_new/max(full_new,1) >= 0.95*pool_old/max(full_old,1) else 'CHECK'} (threshold: at least 95% of the old share)")
    L.append("")
    L.append("## 6. Speed (median ms per request, limit=1)")
    L.append(f"- old (Hebrew, local engine): {statistics.median(ms_old):.0f} ms; MACULA (all 12 filter sets): {statistics.median(ms_new):.0f} ms")
    a.out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    sys.exit(main())
