"""Acceptance report for the structure base switch (NC exit, step 3; design: internal-docs/nc-exit-step3-structure-design.md).

Compares STRUCTURE_BASE=bhsa (Context-Fabric: BHSA Hebrew locally, Nestle1904 Greek through the live service) with STRUCTURE_BASE=macula (trees-macula.db) through
the same functions the endpoints call:

  1. COVERAGE   share of verses with a tree, of words with a clause and with a phrase, per corpus (MACULA)
  2. CONTRACT   every key of the engine's passage / syntax / tree / context / search responses is present in the MACULA response
  3. TEXT       the clauses of a verse together hold its words (no word lost, none twice)
  4. SEARCH     who-did-what search: for sampled (Strong's, function) pairs, the verses found by each base (overlap), Hebrew locally, Greek against the live service
  5. STRUCTURE  clauses and phrases per verse, function mix
  6. SPEED      median ms per call

  cd shoresh && .venv/bin/python3 -m macula.compare_structure_bases [--hbo 120] [--grc 40] [--out ../internal-docs/structure-base-comparison.md]
Thresholds are written next to each line as PASS / CHECK; a CHECK is a finding to decide on, not a crash.
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import random
import sqlite3
import statistics
import sys
import time
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
LIVE = os.environ.get("SHORESH_LIVE", "https://shoresh.qombi.com")


def live(path: str):
    """One GET against the live service; a single retry, short timeouts, so a slow edge costs seconds and not minutes."""
    err = None
    for attempt in range(2):
        try:
            with urllib.request.urlopen(urllib.request.Request(f"{LIVE}{path}", headers={"User-Agent": "bcv-query-acceptance/1.0 (curl-compatible)", "Accept": "application/json"}), timeout=25) as r:
                return json.loads(r.read())
        except Exception as e:
            err = e
            time.sleep(3)
    return {"error": str(err)}


def keys(o, prefix=""):
    """The set of key paths of a JSON value (lists contribute their first element), to compare response shapes."""
    out = set()
    if isinstance(o, dict):
        for k, v in o.items():
            out.add(prefix + k)
            out |= keys(v, prefix + k + ".")
    elif isinstance(o, list) and o:
        out |= keys(o[0], prefix + "[].")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--hbo", type=int, default=120)
    ap.add_argument("--grc", type=int, default=12, help="Greek verses compared against the live service (3 requests each)")
    ap.add_argument("--search", type=int, default=25, help="Hebrew Strong's numbers sampled (3 functions each)")
    ap.add_argument("--search-grc", type=int, default=8, help="Greek Strong's numbers sampled against the live service (3 requests each)")
    ap.add_argument("--seed", type=int, default=13)
    ap.add_argument("--out", type=Path, default=HERE.parents[1] / "internal-docs" / "structure-base-comparison.md")
    a = ap.parse_args()
    import trees_macula
    if not trees_macula.available():
        print("trees-macula.db / lexeme-spine-macula.db not found"); return 1
    os.environ.pop("STRUCTURE_BASE", None)
    import corpus
    if not os.path.isdir(os.path.expanduser("~/text-fabric-data/github/ETCBC/nestle1904/tf")):
        # corpus._book_map lists both corpora and fails when Nestle1904 is not on this machine: map the Hebrew books only
        eng = corpus._eng()
        hmap = {corpus._HEBREW_NAME_TO_USFM.get(b.name, b.name).upper(): (b.name, "hebrew") for b in eng.list_books("hebrew")}
        corpus._book_map = lambda: hmap
    rnd = random.Random(a.seed)
    con = trees_macula._con()
    L: list[str] = [f"# Structure base comparison: BHSA / Nestle1904 engine vs MACULA lowfat trees ({time.strftime('%Y-%m-%d')})", "",
                    "Generated by `shoresh/macula/compare_structure_bases.py`. Hebrew: local BHSA engine. Greek: the live service's engine (Nestle1904 is not on the dev box).", ""]

    # 1. coverage -------------------------------------------------------------------------------------------------
    L.append("## 1. Coverage (MACULA trees)")
    cov = {}
    for c, name in (("hbo", "Hebrew"), ("grc", "Greek")):
        verses = con.execute("SELECT COUNT(*) FROM (SELECT DISTINCT book, chapter, verse FROM words WHERE corpus=? AND inserted=0)", (c,)).fetchone()[0]
        with_cl = con.execute("SELECT COUNT(*) FROM (SELECT DISTINCT book, chapter, verse FROM words WHERE corpus=? AND inserted=0 AND cl IS NOT NULL)", (c,)).fetchone()[0]
        words = con.execute("SELECT COUNT(*) FROM words WHERE corpus=? AND inserted=0", (c,)).fetchone()[0]
        in_cl = con.execute("SELECT COUNT(*) FROM words WHERE corpus=? AND inserted=0 AND cl IS NOT NULL", (c,)).fetchone()[0]
        in_ph = con.execute("SELECT COUNT(*) FROM words WHERE corpus=? AND inserted=0 AND (ph IS NOT NULL OR role IS NOT NULL)", (c,)).fetchone()[0]
        cov[c] = (verses, with_cl / max(verses, 1), in_cl / max(words, 1), in_ph / max(words, 1))
        L.append(f"- {name}: {verses} verses, {100*cov[c][1]:.1f}% have a clause; {words} words, {100*cov[c][2]:.1f}% in a clause, {100*cov[c][3]:.1f}% in a role-bearing phrase "
                 f"{'PASS' if cov[c][1] >= 0.98 else 'CHECK'} (threshold: 98% of verses have a clause)")
    L.append("")

    # sample verses -------------------------------------------------------------------------------------------------
    def sample(c, n):
        rows = con.execute("SELECT DISTINCT book, chapter, verse FROM words WHERE corpus=? AND inserted=0", (c,)).fetchall()
        return [tuple(r) for r in rnd.sample(rows, min(n, len(rows)))]
    hv, gv = sample("hbo", a.hbo), sample("grc", a.grc)

    # 2./3./5./6. per verse ----------------------------------------------------------------------------------------
    miss = collections.defaultdict(set)
    ms = collections.defaultdict(list)
    struct = {"bhsa": collections.Counter(), "macula": collections.Counter()}
    fnmix = {"bhsa": collections.Counter(), "macula": collections.Counter()}
    text_bad = 0
    text_checked = 0

    def walk(res, base, c):
        d = res.get("data", {}) if isinstance(res, dict) else {}
        cls = d.get("clauses") or [x for s in d.get("sentences", []) for x in s["clauses"]]
        for cl in cls:
            struct[base][c + ":clauses"] += 1
            for p in cl["phrases"]:
                struct[base][c + ":phrases"] += 1
                fnmix[base][(c, p["function"])] += 1
        struct[base][c + ":verses"] += 1

    def compare(c, ref, fetch_old):
        book, ch, v = ref
        checks = [("passage", trees_macula.passage, lambda: fetch_old("structure", book, ch, v)),
                  ("syntax", trees_macula.syntax, lambda: fetch_old("syntax", book, ch, v)),
                  ("tree", trees_macula.tree, lambda: fetch_old("tree", book, ch, v)),
                  ("context", lambda b, c_, v_: trees_macula.context(b, c_, v_, 1), lambda: fetch_old("word", book, ch, v))]
        for name, new_f, old_f in checks:
            t = time.perf_counter(); new = new_f(book, ch, v); ms[("macula", name)].append(1000 * (time.perf_counter() - t))
            t = time.perf_counter(); old = old_f(); ms[("bhsa", name)].append(1000 * (time.perf_counter() - t))
            if "error" in old or "error" in new:
                if "error" in new and "error" not in old:
                    miss[(c, name)].add("(macula error: " + str(new["error"])[:60] + ")")
                continue
            if name == "context":
                need = {"word", "clause", "phrase", "sentence"}
                have = set(new["data"]) & need
                if have != need and set(old["data"]) >= {"clause", "phrase"}:
                    miss[(c, name)] |= {f"missing {x}" for x in need - have}
                for k in ("word", "clause"):
                    for f in keys(old["data"].get(k, {})) - keys(new["data"].get(k, {})):
                        if not f.startswith("features.") or f.split(".")[1] in ("typ", "function", "rela", "kind", "otype"):
                            miss[(c, name)].add(f"{k}.{f}")
            else:
                for k in keys(old) - keys(new):
                    miss[(c, name)].add(k)
            if name == "syntax":
                walk(old, "bhsa", c); walk(new, "macula", c)
        # text: every non-inserted word of the verse is in exactly one clause
        nonlocal text_bad, text_checked
        words = con.execute("SELECT COUNT(*) FROM words WHERE corpus=? AND book=? AND chapter=? AND verse=? AND inserted=0", ("hbo" if c == "hebrew" else "grc", book, ch, v)).fetchone()[0]
        cl_words = sum(len(p["words"]) for cl in trees_macula.syntax(book, ch, v).get("data", {}).get("clauses", []) for p in cl["phrases"])
        text_checked += 1
        text_bad += words != cl_words

    def old_hebrew(kind, book, ch, v):
        try:
            return {"structure": corpus.passage, "syntax": corpus.syntax, "tree": corpus.tree, "word": lambda b, c_, v_: corpus.context(b, c_, v_, 1)}[kind](book, ch, v)
        except Exception as e:
            return {"error": str(e)}

    def old_greek(kind, book, ch, v):
        path = {"structure": f"/structure/{book}/{ch}/{v}", "syntax": f"/structure/{book}/{ch}/{v}/syntax", "tree": f"/verse/{book}/{ch}/{v}/tree",
                "word": f"/structure/{book}/{ch}/{v}/word/1"}[kind]
        time.sleep(0.8)
        r = live(path)
        return r if "corpus" in r else {"error": r.get("detail") or r.get("error") or "no data"}

    for i, ref in enumerate(hv, 1):
        compare("hebrew", ref, old_hebrew)
        if i % 25 == 0:
            print(f"  hebrew verses {i}/{len(hv)}", file=sys.stderr)
    for i, ref in enumerate(gv, 1):
        compare("greek", ref, old_greek)
        print(f"  greek verses {i}/{len(gv)}", file=sys.stderr)

    L.append("## 2. Contract (keys the engine's responses have that MACULA's lack)")
    bad = False
    for c in ("hebrew", "greek"):
        for name in ("passage", "syntax", "tree", "context"):
            m = sorted(miss.get((c, name), set()))
            bad |= bool([x for x in m if not x.startswith("(macula error")])
            L.append(f"- {c} {name}: " + ("none" if not m else ", ".join(m[:12]) + (" ..." if len(m) > 12 else "")))
    L.append(f"- {'PASS' if not bad else 'CHECK'}: " + ("every key present" if not bad else "see the missing keys above"))
    L.append("")
    L.append("## 3. Text: every word of a verse sits in exactly one clause")
    L.append(f"- {text_checked - text_bad}/{text_checked} sampled verses list every word exactly once {'PASS' if text_bad <= 0.05 * text_checked else 'CHECK'} "
             "(threshold 95%; the exceptions are clauses that run across a verse boundary)")
    L.append("")
    L.append("## 4. Clause and phrase structure (sampled verses, syntax view)")
    for c in ("hebrew", "greek"):
        v_o, v_n = struct["bhsa"][c + ":verses"] or 1, struct["macula"][c + ":verses"] or 1
        L.append(f"- {c}: clauses per verse BHSA/Nestle {struct['bhsa'][c+':clauses']/v_o:.2f}, MACULA {struct['macula'][c+':clauses']/v_n:.2f}; "
                 f"phrases per verse {struct['bhsa'][c+':phrases']/v_o:.2f} vs {struct['macula'][c+':phrases']/v_n:.2f}")
        for base in ("bhsa", "macula"):
            top = [f"{f or 'none'} {n}" for (cc, f), n in fnmix[base].most_common(40) if cc == c][:8]
            L.append(f"  - function mix {base}: " + ", ".join(top))
    L.append("")

    # 4. search -----------------------------------------------------------------------------------------------------
    L.append("## 5. Who-did-what search (verses found per Strong's x function)")
    spine = trees_macula._con()
    hs = [r[0] for r in spine.execute("SELECT strong FROM sp.spine_words WHERE lexeme LIKE 'hbo:%' AND strong IS NOT NULL GROUP BY strong HAVING COUNT(*)>=25")]
    gs = [r[0] for r in spine.execute("SELECT CAST(strong AS INTEGER) FROM words WHERE corpus='grc' AND strong IS NOT NULL GROUP BY CAST(strong AS INTEGER) HAVING COUNT(*)>=25")]
    verb_strongs = {r[0] for r in spine.execute("SELECT DISTINCT strong_n FROM words WHERE corpus='hbo' AND class='verb'")} | \
                   {r[0] for r in spine.execute("SELECT DISTINCT strong_n FROM words WHERE corpus='grc' AND class='verb'")}
    rows = []
    for c, pool, funcs in (("hebrew", hs, ("Subject", "Object", "Verb")), ("greek", gs, ("Subject", "Object", "Verb"))):
        for n in rnd.sample(pool, min(a.search if c == "hebrew" else a.search_grc, len(pool))):
            for fn in funcs:
                if fn == "Verb" and n not in verb_strongs:
                    continue                                   # a noun never fills the verb slot; BHSA's Pred also holds nominal predicates
                code = ("H" if c == "hebrew" else "G") + f"{n:04d}"
                new = trees_macula.syntax_search(function=fn, strong=code, limit=100000)
                if c == "hebrew":
                    old = corpus.syntax_search(function=("Pred" if fn == "Verb" else fn), strong=code, limit=100000)
                else:
                    time.sleep(0.8)
                    old = live(f"/syntax/search?strong={code}&function={fn}&limit=500")      # the live service caps at 500: pairs that hit the cap are skipped below
                    old = old if "corpus" in old else {"error": "live"}
                if "error" in old or "error" in new or "error" in old.get("data", {}):
                    continue
                refs = lambda r: {(x["book"], x["chapter"], x["verse"]) for x in r["data"]["clauses"]}
                o, nw = refs(old), refs(new)
                if c == "greek" and (len(old["data"]["clauses"]) >= 500 or len(new["data"]["clauses"]) >= 500):
                    continue                                   # capped at 500 on the live side: not comparable
                if o or nw:
                    rows.append((c, fn, len(o), len(nw), len(o & nw)))
    for c in ("hebrew", "greek"):
        for fn in ("Subject", "Object", "Verb"):
            sel = [r for r in rows if r[0] == c and r[1] == fn]
            if not sel:
                continue
            o, nw, both = sum(r[2] for r in sel), sum(r[3] for r in sel), sum(r[4] for r in sel)
            L.append(f"- {c} {fn}: {len(sel)} words with hits; verses BHSA/Nestle {o}, MACULA {nw}, both {both}; "
                     f"recall of the old base {100*both/max(o,1):.0f}%, precision {100*both/max(nw,1):.0f}%")
    tot_o = sum(r[2] for r in rows); tot_b = sum(r[4] for r in rows)
    L.append(f"- overall recall of the old base's verses: {100*tot_b/max(tot_o,1):.0f}% (reported, not gated: the two annotations legitimately differ)")
    L.append("")

    L.append("## 6. Speed (median ms per call)")
    for name in ("passage", "syntax", "tree", "context"):
        o = statistics.median(ms[("bhsa", name)]) if ms[("bhsa", name)] else float("nan")
        n = statistics.median(ms[("macula", name)]) if ms[("macula", name)] else float("nan")
        L.append(f"- {name}: old {o:.0f} ms (Hebrew local + Greek over HTTP), MACULA {n:.1f} ms")
    a.out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    sys.exit(main())
