#!/usr/bin/env bash
# Write Cloudflare's published address ranges as a Caddy snippet and reload Caddy if they changed.
#
# The snippet defines the matcher @viaCF (request arrives from a Cloudflare address). The Caddyfile uses it so
# that CF-Connecting-IP (the visitor's real address) is trusted ONLY on such requests, never on direct ones:
#
#   import /etc/caddy/cloudflare-ips.caddy         # at the top, once
#   example.com {
#       import cf-origin                            # defines @viaCF for this site
#       handle @viaCF { reverse_proxy app:8080 { header_up X-Forwarded-For {http.request.header.CF-Connecting-IP} } }
#       handle        { reverse_proxy app:8080 }
#   }
#
# Run as root (installed on the host as /usr/local/sbin/update-cloudflare-ips, weekly via a systemd timer).
# The new file is validated with `caddy validate` before it replaces the old one; a failed fetch or an
# invalid file leaves the running configuration untouched. Needs: curl, caddy.
set -euo pipefail
OUT="${CF_IPS_OUT:-/etc/caddy/cloudflare-ips.caddy}"
CADDYFILE="${CADDYFILE:-/etc/caddy/Caddyfile}"
TMP="$(mktemp)"; trap 'rm -f "$TMP"' EXIT

v4="$(curl -fsS -m 30 https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS -m 30 https://www.cloudflare.com/ips-v6)"
ranges="$(printf '%s\n%s\n' "$v4" "$v6" | grep -E '^[0-9a-fA-F:.]+/[0-9]+$' | sort -u | tr '\n' ' ')"
n="$(wc -w <<<"$ranges")"
[ "$n" -ge 10 ] || { echo "only $n ranges fetched; refusing to write" >&2; exit 1; }

printf '# generated by deploy/cloudflare_ips_caddy.sh on %s (%s ranges); do not edit\n(cf-origin) {\n\t@viaCF remote_ip %s\n}\n' \
  "$(date -u +%FT%TZ)" "$n" "$ranges" >"$TMP"

if [ -f "$OUT" ] && diff -q <(tail -n +2 "$OUT") <(tail -n +2 "$TMP") >/dev/null; then
  echo "unchanged ($n ranges)"; exit 0
fi
cp -p "$OUT" "$OUT.prev" 2>/dev/null || true
install -m 644 "$TMP" "$OUT"
if ! caddy validate --adapter caddyfile --config "$CADDYFILE" >/dev/null 2>&1; then
  echo "new range file makes the Caddyfile invalid; restoring the previous one" >&2
  [ -f "$OUT.prev" ] && cp -p "$OUT.prev" "$OUT"; exit 1
fi
systemctl reload caddy && echo "updated ($n ranges), caddy reloaded"
